# Часть 9 - главный код
lines = []
lines.append("")
lines.append("")
lines.append("parsed_parser = None")
lines.append("")
lines.append("")
lines.append("def parse_pdf_to_db(pdf_path, output_stats=True):")
lines.append("    global parsed_parser")
lines.append('    print(chr(10) + chr(61)*60)')
lines.append('    print("ШАГ 1: Парсинг PDF документа")')
lines.append('    print(chr(61)*60)')
lines.append("    parser = PDFParser(pdf_path)")
lines.append("    parsed_parser = parser")
lines.append("    parsed = parser.parse()")
lines.append("    if not parsed or not parsed.chapters:")
lines.append('        print("ВНИМАНИЕ: Не удалось извлечь главы из PDF.")')
lines.append("        return None")
lines.append('    print(chr(10) + chr(61)*60)')
lines.append('    print("ШАГ 2: Загрузка в базу данных")')
lines.append('    print(chr(61)*60)')
lines.append("    loader = DatabaseLoader()")
lines.append("    loader.connect()")
lines.append("    try:")
lines.append("        stats = loader.load_document(parsed)")
lines.append("        if output_stats:")
lines.append('            print(chr(10) + chr(61)*60)')
lines.append('            print("Загрузка завершена успешно!")')
lines.append('            print(f"   Документов: {stats[chr(100)+chr(111)+chr(99)+chr(115)+chr(95)+chr(97)+chr(100)+chr(100)+chr(101)+chr(100)]}")')
lines.append('            print(f"   Фрагментов: {stats[chr(102)+chr(114)+chr(97)+chr(103)+chr(109)+chr(101)+chr(110)+chr(116)+chr(115)+chr(95)+chr(97)+chr(100)+chr(100)+chr(101)+chr(100)]}")')
lines.append('            print(f"   Алиасов: {stats[chr(97)+chr(108)+chr(105)+chr(97)+chr(115)+chr(95)+chr(97)+chr(100)+chr(100)+chr(101)+chr(100)]}")')
lines.append('            print(f"   Snippets: {stats[chr(115)+chr(110)+chr(105)+chr(112)+chr(112)+chr(101)+chr(116)+chr(115)+chr(95)+chr(97)+chr(100)+chr(100)+chr(101)+chr(100)]}")')
lines.append('            print(chr(61)*60 + chr(10))')
lines.append("        return stats")
lines.append("    finally:")
lines.append("        loader.close()")

with open(r"C:\1C_LLM\ckb\src\pdf_parser.py", "a", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("Часть 9 создана!")
