# Часть 3 - метод parse и вспомогательные методы
lines = []
lines.append("")
lines.append("    def parse(self):")
lines.append('        print(f"\\n{chr(61)*60}")')
lines.append('        print(f"Парсинг PDF: {self.pdf_path.name}")')
lines.append('        print(f"{chr(61)*60}")')
lines.append("")
lines.append("        chapters = []")
lines.append("        current_chapter = None")
lines.append("        page_num = 0")
lines.append("")
lines.append('        with pdfplumber.open(str(self.pdf_path)) as pdf:')
lines.append("            total_pages = len(pdf.pages)")
lines.append('            print(f"Всего страниц: {total_pages}\\n")')
lines.append("")
lines.append("            for i, page in enumerate(pdf.pages):")
lines.append("                page_num = i + 1")
lines.append("                text = page.extract_text()")
lines.append("                if not text:")
lines.append("                    continue")
lines.append("")
lines.append('                lines = text.split(chr(10))')
lines.append("")
lines.append("                for line in lines:")
lines.append("                    line = line.strip()")
lines.append("                    if not line or len(line) > 200:")
lines.append("                        continue")
lines.append("")
lines.append("                    heading_level = self._detect_heading_level(line)")
lines.append("")
lines.append("                    if heading_level and heading_level <= 3:")
lines.append("                        title = self._clean_title(line)")
lines.append("")
lines.append("                        if current_chapter:")
lines.append("                            chapters.append(current_chapter)")
lines.append("")
lines.append("                        current_chapter = Chapter(title=title, level=heading_level, content='')")
lines.append('                        print(f"[{page_num}] Глава {heading_level}: {title[:80]}")')
lines.append("")
lines.append("                if current_chapter:")
lines.append("                    code_blocks = self._extract_code_blocks(page)")
lines.append("                    for cb in code_blocks:")
lines.append("                        current_chapter.code_blocks.append(cb)")
lines.append("")
lines.append("                    methods = self._extract_methods(text)")
lines.append("                    for m in methods:")
lines.append("                        current_chapter.methods.append(m)")
lines.append("")
lines.append("                if current_chapter and page_num % 3 == 0:")
lines.append("                    if current_chapter.content and text:")
lines.append('                        current_chapter.content += chr(10)+chr(10) + text[:500]')
lines.append("")
lines.append("            if current_chapter:")
lines.append("                chapters.append(current_chapter)")
lines.append("")
lines.append("        self.parsed = ParsedDocument(title=self._extract_title_from_pdf(), chapters=chapters, total_pages=page_num)")
lines.append("")
lines.append("        total_methods = sum(len(c.methods) for c in chapters)")
lines.append("        total_code = sum(len(c.code_blocks) for c in chapters)")
lines.append('        print(f"\\n{chr(61)*60}")')
lines.append('        print("Результат парсинга:")')
lines.append('        print(f"  Главы/разделы: {len(chapters)}")')
lines.append('        print(f"  Методы найдены: {total_methods}")')
lines.append('        print(f"  Блоки кода: {total_code}")')
lines.append('        print(f"{chr(61)*60}\\n")')
lines.append("        return self.parsed")

with open(r"C:\1C_LLM\ckb\src\pdf_parser.py", "a", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("Часть 3 создана!")
