# Создаем pdf_parser.py - Часть 2 (класс PDFParser)
import os

lines = []
lines.append("")
lines.append("")
lines.append("class PDFParser:")
lines.append("    CODE_KEYWORDS = {")
lines.append('        "Процедура", "Функция", "КонецПроцедуры", "КонецФункции",')
lines.append('        "Если", "Тогда", "Иначе", "КонецЕсли",')
lines.append('        "Для", "Цикл", "По", "КонецЦикла",')
lines.append('        "Новый", "Выбрать", "Записать", "Провести",')
lines.append('        "РегистрыНакопления", "РегистрБухгалтерии",')
lines.append('        "Запрос", "ТаблицаДокладов", "Форма",')
lines.append("    }")
lines.append("")
lines.append("    TAG_PATTERNS = {")
lines.append('        "code": [r"код|пример|блок|процедура|функция"],')
lines.append('        "howto": [r"как\\s+создать|добавление|настройка|инструкция"],')
lines.append('        "api": [r"метод|свойство|объект|класс|тип"],')
lines.append('        "syntax": [r"синтаксис|описание|параметр|возвращает"],')
lines.append('        "error": [r"ошибка|исключение|не удалось|не найден"],')
lines.append("    }")
lines.append("")
lines.append("    ALIASES = {")
lines.append('        "регистр накопления": ["накопительный регистр", "регистр-накопление"],')
lines.append('        "проводка": ["движение документа", "запись регистра"],')
lines.append('        "справочник": ["справочник-ссылок", "reference"],')
lines.append("    }")
lines.append("")
lines.append("    def __init__(self, pdf_path: str):")
lines.append("        self.pdf_path = Path(pdf_path)")
lines.append("        if not self.pdf_path.exists():")
lines.append('            raise FileNotFoundError(f"PDF файл не найден: {pdf_path}")')
lines.append("        self.parsed = None")

with open(r"C:\1C_LLM\ckb\src\pdf_parser.py", "a", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("Часть 2 создана!")
