# Часть 4 - вспомогательные методы PDFParser
lines = []
lines.append("")
lines.append("    def _detect_heading_level(self, line):")
lines.append('        if re.match(r"^Заняти[ея]\\s+\\d+", line):')
lines.append("            return 2")
lines.append('        if re.match(r"^Глава\\s+\\d+", line):')
lines.append("            return 1")
lines.append('        match = re.match(r"^\\d+\\.\\d{1,2}\\.", line)')
lines.append("        if match:")
lines.append('            dots = len(re.findall(r"\\.", line[:10]))')
lines.append("            return min(dots + 1, 4)")
lines.append('        if len(line) < 80 and not line.endswith(".") and not line.endswith(","):')
lines.append("            return 3")
lines.append("        return None")
lines.append("")
lines.append("    def _clean_title(self, title):")
lines.append('        title = re.sub(r"\\(\\d+:\\d+\\)", "", title)')
lines.append('        title = re.sub(r"\\s*[\\.\\-\\u2013\\u2014]+\\s*", " ", title)')
lines.append('        title = re.sub(r"\\s+", " ", title).strip()')
lines.append("        return title")
lines.append("")
lines.append("    def _extract_code_blocks(self, page):")
lines.append("        blocks = []")
lines.append("        tables = page.extract_tables()")
lines.append("        for table in tables:")
lines.append("            if not table or len(table) < 2:")
lines.append("                continue")
lines.append("            table_text = []")
lines.append("            for row in table:")
lines.append("                if row:")
lines.append('                    cell_text = " ".join(str(c) for c in row if c)')
lines.append("                    if cell_text and len(cell_text) > 10:")
lines.append("                        table_text.append(cell_text)")
lines.append("            full_text = chr(10).join(table_text)")
lines.append("            has_code_keywords = any(kw in full_text for kw in self.CODE_KEYWORDS)")
lines.append('            if has_code_keywords and len(full_text) > 50:')
lines.append('                blocks.append(CodeBlock(code=full_text[:2000], description="Извлечено из таблицы PDF"))')
lines.append("        return blocks")
lines.append("")
lines.append("    def _extract_methods(self, text):")
lines.append("        methods = []")
lines.append("        seen_names = set()")
lines.append('        pattern = r"(Процедура|Функция)\\s+(\\w+)(\\([^)]*\\))?"')
lines.append("        for match in re.finditer(pattern, text):")
lines.append("            method_type = match.group(1)")
lines.append("            name = match.group(2)")
lines.append('            signature = match.group(3) or ""')
lines.append("            if name not in seen_names and len(name) > 2:")
lines.append("                seen_names.add(name)")
lines.append("                methods.append(MethodSignature(name=name, signature=signature.strip(), description=f'{method_type} {name}{signature}', category='language'))")
lines.append("        return methods")
lines.append("")
lines.append("    def _extract_title_from_pdf(self):")
lines.append("        try:")
lines.append('            with pdfplumber.open(str(self.pdf_path)) as pdf:')
lines.append("                first_page = pdf.pages[0]")
lines.append('                text = first_page.extract_text() or ""')
lines.append('                for line in text.split(chr(10))[:20]:')
lines.append("                    line = line.strip()")
lines.append("                    if len(line) > 10 and len(line) < 100:")
lines.append('                        if any(kw in line.lower() for kw in ["пособие", "руководство"]):')
lines.append("                            return self._clean_title(line)")
lines.append("        except Exception:")
lines.append("            pass")
lines.append('        name = self.pdf_path.stem.replace("_", " ")')
lines.append("        return self._clean_title(name)")
lines.append("")
lines.append("    def get_tags_for_text(self, text):")
lines.append("        tags = []")
lines.append("        text_lower = text.lower()")
lines.append("        for tag, patterns in self.TAG_PATTERNS.items():")
lines.append("            for pattern in patterns:")
lines.append("                if re.search(pattern, text_lower, re.IGNORECASE):")
lines.append("                    if tag not in tags:")
lines.append("                        tags.append(tag)")
lines.append("                    break")
lines.append("        return tags")
lines.append("")
lines.append("    def get_aliases_for_method(self, method_name):")
lines.append("        aliases = {}")
lines.append("        aliases[method_name] = 2.0")
lines.append("        for term, alias_list in self.ALIASES.items():")
lines.append("            if term in method_name.lower() or method_name.lower() in term:")
lines.append("                for alias in alias_list:")
lines.append("                    aliases[alias] = 1.5")
lines.append("        return aliases")

with open(r"C:\1C_LLM\ckb\src\pdf_parser.py", "a", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("Часть 4 создана!")
