# Часть 7 - методы DatabaseLoader (часть 2)
lines = []
lines.append("")
lines.append("    def _insert_fragment(self, method, category_id, related_doc_id):")
lines.append("        cur = self.conn.cursor()")
lines.append('        cur.execute("SELECT id FROM doc_fragments WHERE name = %s AND fragment_type = %s", (method.name, "method"))')
lines.append("        if cur.fetchone():")
lines.append("            cur.close()")
lines.append("            return None")
lines.append("        try:")
lines.append('            cur.execute("INSERT INTO doc_fragments (category_id, fragment_type, name, signature, content, related_doc_id, full_text_search, created_at) VALUES (%s, %s, %s, %s, %s, %s, to_tsvector(chr(39)+russian+chr(39), %s), NOW()) RETURNING id", (category_id, "method", method.name, method.signature[:5000], method.description[:10000], related_doc_id, method.description))')
lines.append("            frag_id = cur.fetchone()[0]")
lines.append("            cur.close()")
lines.append("            return frag_id")
lines.append("        except Exception as e:")
lines.append('            print(f"  Ошибка вставки doc_fragments: {e}")')
lines.append("            cur.close()")
lines.append("            return None")
lines.append("")
lines.append("    def _insert_alias(self, alias_name, target_type, target_id, weight=1.0):")
lines.append("        cur = self.conn.cursor()")
lines.append("        try:")
lines.append('            cur.execute("INSERT INTO search_aliases (alias_name, target_type, target_id, weight, active) VALUES (%s, %s, %s, %s, true) ON CONFLICT (alias_name, target_type) DO UPDATE SET weight = EXCLUDED.weight, updated_at = NOW()", (alias_name, target_type, target_id, weight))')
lines.append("            cur.close()")
lines.append("        except Exception:")
lines.append("            cur.close()")

with open(r"C:\1C_LLM\ckb\src\pdf_parser.py", "a", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("Часть 7 создана!")
