# Часть 8 - методы DatabaseLoader (часть 3) и главный код
lines = []
lines.append("")
lines.append("    def _insert_snippet(self, chapter, code_block):")
lines.append("        cur = self.conn.cursor()")
lines.append('        question = f"Как использовать {chapter.title}: {code_block.description}"[:500]')
lines.append('        answer = f"Пример использования в контексте: " + chr(10) + chr(10) + code_block.code[:5000][:10000]')
lines.append("        tags = parsed_parser.get_tags_for_text(code_block.code)")
lines.append("        try:")
lines.append('            cur.execute("INSERT INTO knowledge_snippets (question, answer, tags, category, confidence, is_verified, created_at) VALUES (%s, %s, %s, language, 0.8, false, NOW()) RETURNING id", (question, answer, tags))')
lines.append("            snippet_id = cur.fetchone()[0]")
lines.append("            cur.close()")
lines.append("            return snippet_id")
lines.append("        except Exception as e:")
lines.append('            print(f"  Ошибка вставки knowledge_snippets: {e}")')
lines.append("            cur.close()")
lines.append("            return None")
lines.append("")
lines.append("    def _get_combined_tags(self, chapter):")
lines.append("        tags = set()")
lines.append("        for text in [chapter.title]:")
lines.append("            for tag in parsed_parser.get_tags_for_text(text):")
lines.append("                tags.add(tag)")
lines.append("        for method in chapter.methods:")
lines.append("            for tag in parsed_parser.get_tags_for_text(method.description):")
lines.append("                tags.add(tag)")
lines.append("        for code_block in chapter.code_blocks:")
lines.append("            for tag in parsed_parser.get_tags_for_text(code_block.code):")
lines.append("                tags.add(tag)")
lines.append("        if chapter.code_blocks:")
lines.append('            tags.add("code")')
lines.append("        return list(tags)")
lines.append("")
lines.append("    def _generate_aliases_for_chapter(self, title):")
lines.append("        aliases = {}")
lines.append("        aliases[title] = 2.0")
lines.append('        words = re.findall(r"\\b\\w+\\b", title)')
lines.append("        for word in words:")
lines.append("            if len(word) > 3:")
lines.append("                aliases[word.lower()] = 1.5")
lines.append("        return aliases")

with open(r"C:\1C_LLM\ckb\src\pdf_parser.py", "a", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("Часть 8 создана!")
