# Часть 5 - класс DatabaseLoader
lines = []
lines.append("")
lines.append("")
lines.append("class DatabaseLoader:")
lines.append("    def __init__(self):")
lines.append("        self.db_config = get_db_config()")
lines.append("        self.conn = None")
lines.append("")
lines.append("    def connect(self):")
lines.append("        self.conn = psycopg2.connect(**self.db_config)")
lines.append("        self.conn.autocommit = True")
lines.append("")
lines.append("    def close(self):")
lines.append("        if self.conn:")
lines.append("            self.conn.close()")
lines.append("")
lines.append("    def load_document(self, parsed):")
lines.append('        stats = {"docs_added": 0, "fragments_added": 0, "aliases_added": 0, "snippets_added": 0}')
lines.append("        cur = self.conn.cursor()")
lines.append('        category_id = self._get_or_create_category("language")')
lines.append("")
lines.append("        for chapter in parsed.chapters:")
lines.append("            doc_id = self._insert_doc(chapter, category_id)")
lines.append("            if doc_id:")
lines.append('                stats["docs_added"] += 1')
lines.append("                aliases = self._generate_aliases_for_chapter(chapter.title)")
lines.append("                for alias, weight in aliases.items():")
lines.append('                    self._insert_alias(alias, "doc", doc_id, weight)')
lines.append('                    stats["aliases_added"] += 1')
lines.append("")
lines.append("            for method in chapter.methods:")
lines.append("                frag_id = self._insert_fragment(method, category_id, doc_id)")
lines.append("                if frag_id:")
lines.append('                    stats["fragments_added"] += 1')
lines.append("                    aliases = parsed_parser.get_aliases_for_method(method.name)")
lines.append("                    for alias, weight in aliases.items():")
lines.append('                        self._insert_alias(alias, "fragment", frag_id, weight)')
lines.append('                        stats["aliases_added"] += 1')
lines.append("")
lines.append("            for code_block in chapter.code_blocks:")
lines.append("                snippet_id = self._insert_snippet(chapter, code_block)")
lines.append("                if snippet_id:")
lines.append('                    stats["snippets_added"] += 1')
lines.append("")
lines.append("        cur.close()")
lines.append('        print(f"\\n{chr(61)*60}")')
lines.append('        print("Статистика загрузки:")')
lines.append('        for key, value in stats.items():')
lines.append('            print(f"  {key}: {value}")')
lines.append('        print(f"{chr(61)*60}\\n")')
lines.append("        return stats")

with open(r"C:\1C_LLM\ckb\src\pdf_parser.py", "a", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("Часть 5 создана!")
