# Часть 6 - методы DatabaseLoader (часть 1)
lines = []
lines.append("")
lines.append("    def _get_or_create_category(self, code):")
lines.append("        cur = self.conn.cursor()")
lines.append('        cur.execute("SELECT id FROM doc_categories WHERE code = %s", (code,))')
lines.append("        row = cur.fetchone()")
lines.append("        if row:")
lines.append("            cur.close()")
lines.append("            return row[0]")
lines.append("        names = {'language': 'Язык БСЛ', 'platform': 'Платформа 1С', 'its': 'ИТС', 'methodology': 'Методология'}")
lines.append("        descriptions = {'language': 'Синтаксис языка, типы данных, встроенные объекты', 'platform': 'COM-интерфейсы, HTTP-сервисы, файловые операции', 'its': 'Материалы с портала Интеграция и Технологии', 'methodology': 'Бухгалтерский учёт, НД/НР, методические рекомендации'}")
lines.append('        cur.execute("INSERT INTO doc_categories (code, name, description) VALUES (%s, %s, %s) RETURNING id", (code, names.get(code, code), descriptions.get(code, "")))')
lines.append("        cat_id = cur.fetchone()[0]")
lines.append("        cur.close()")
lines.append("        return cat_id")
lines.append("")
lines.append("    def _insert_doc(self, chapter, category_id):")
lines.append("        tags = self._get_combined_tags(chapter)")
lines.append("        cur = self.conn.cursor()")
lines.append('        cur.execute("SELECT id FROM docs WHERE title = %s", (chapter.title,))')
lines.append("        row = cur.fetchone()")
lines.append("        if row:")
lines.append("            cur.close()")
lines.append("            return row[0]")
lines.append("        content = chapter.content or ''")
lines.append("        if chapter.code_blocks:")
lines.append('            content += chr(10)+chr(10) + "Примеры кода:" + chr(10) + chr(10).join(cb.code[:500] for cb in chapter.code_blocks[:3])')
lines.append("        try:")
lines.append('            cur.execute("INSERT INTO docs (category_id, title, content, tags, created_at) VALUES (%s, %s, %s, %s, NOW()) RETURNING id", (category_id, chapter.title, content[:100000], tags))')
lines.append("            doc_id = cur.fetchone()[0]")
lines.append("            cur.close()")
lines.append("            return doc_id")
lines.append("        except Exception as e:")
lines.append('            print(f"  Ошибка вставки docs: {e}")')
lines.append("            cur.close()")
lines.append("            return None")

with open(r"C:\1C_LLM\ckb\src\pdf_parser.py", "a", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("Часть 6 создана!")
