# Создаем pdf_parser.py
import os

lines = []
lines.append('"""')
lines.append("PDF Parser для извлечения структурных элементов из документации по 1С.")
lines.append("")
lines.append("Извлекает:")
lines.append("- Главы и разделы (загружаются в docs)")
lines.append("- Функции, методы, классы (загружаются в doc_fragments)")
lines.append("- Примеры кода (сохраняются как snippets)")
lines.append("- Алиасы для поиска (добавляются в search_aliases)")
lines.append('"""')
lines.append("")
lines.append("import os")
lines.append("import sys")
lines.append("import re")
lines.append("from pathlib import Path")
lines.append("from dataclasses import dataclass, field")
lines.append("from typing import List, Optional, Dict")
lines.append("")
lines.append("try:")
lines.append("    import pdfplumber")
lines.append("except ImportError:")
lines.append('    print("Ошибка: pip install pdfplumber")')
lines.append("    sys.exit(1)")
lines.append("")
lines.append("sys.path.insert(0, str(Path(__file__).parent / 'src'))")
lines.append("import psycopg2")
lines.append("from database import get_db_config")
lines.append("")
lines.append("")
lines.append("@dataclass")
lines.append("class CodeBlock:")
lines.append("    code: str")
lines.append('    language: str = "1c"')
lines.append('    description: str = ""')
lines.append('    parent_title: str = ""')
lines.append("")
lines.append("")
lines.append("@dataclass")
lines.append("class MethodSignature:")
lines.append("    name: str")
lines.append('    signature: str = ""')
lines.append('    description: str = ""')
lines.append('    category: str = "language"')
lines.append("")
lines.append("")
lines.append("@dataclass")
lines.append("class Chapter:")
lines.append("    title: str")
lines.append("    level: int = 1")
lines.append('    content: str = ""')
lines.append("    methods: List[MethodSignature] = field(default_factory=list)")
lines.append("    code_blocks: List[CodeBlock] = field(default_factory=list)")
lines.append("")
lines.append("")
lines.append("@dataclass")
lines.append("class ParsedDocument:")
lines.append("    title: str")
lines.append("    chapters: List[Chapter] = field(default_factory=list)")
lines.append("    total_pages: int = 0")

with open(r"C:\1C_LLM\ckb\src\pdf_parser.py", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("Часть 1 создана!")
